"""
lo saque de chatgpt la verda
Vocabulario RPG (~1200 palabras) para el sistema de autocompletado.
"""

BLACKLIST_WORDS = [
    "idiota", "estupido","estupida" , "maldita", "mierda", "basura",
    "imbecil", "pendejo","pendeja", "cabron","cabrona", "puta",
    "inutil", "animal", "bestia", "hitler", "nigga", "prostituta",
    "prostituto", "vagina", "pussy", "pene", "dick", "rape", "bitch",
    "malparido", "malparida", "67", "six", "sevem", "sixseven", "coito",
    "sex", "sexo", "sexo2", "Trabajo", "chamba", "job", "agarrar la pala",
    
]

RPG_VOCABULARY = [
    # ── Clases y razas ──────────────────────────
    "guerrero", "guerrera", "mago", "maga", "hechicero", "hechicera",
    "arquero", "arquera", "paladin", "paladina", "druida", "druida",
    "barbaro", "barbara", "bardo", "bardesa", "clerigo", "cleriga",
    "picaro", "picara", "monje", "monjesa", "nigromante", "nigromanta",
    "cazador", "cazadora", "explorador", "exploradora", "guardian",
    "guardiana", "titan", "titana", "caballero", "caballera",
    "lanzero", "lanzera", "espadachin", "hechizero",
    # Razas
    "elfo", "elfa", "enano", "enana", "hobbit", "gnomo", "gnoma",
    "orco", "orca", "troll", "hada", "fairy", "dragones", "draconido",
    "licántropo", "vampiro", "vampira", "semielfo", "semiorco",
    "tiefling", "aarakocra", "genasi", "goliath", "triton",
    # ── Habilidades y magia ──────────────────────
    "ataque", "ataques", "atacar", "atacante", "atacantes",
    "defensa", "defender", "defensas", "defensivo", "defensiva",
    "hechizo", "hechizos", "lanzar", "lanzamiento", "lanzador",
    "magia", "magico", "magica", "magicer", "magister",
    "encantamiento", "encantado", "encantadora", "encantar",
    "maldicion", "maldecir", "maldito", "maldiciente",
    "bendicion", "bendecir", "bendito", "bendita",
    "curacion", "curar", "curado", "curada", "curandero",
    "veneno", "envenenar", "envenenado", "venenos",
    "escudo", "escudos", "escudar", "proteger", "proteccion",
    "fuerza", "fuerte", "poder", "poderes", "poderoso",
    "agilidad", "agil", "velocidad", "veloz", "rapido",
    "inteligencia", "inteligente", "sabiduria", "sabio",
    "carisma", "carismatico", "intimidar", "intimidacion",
    "sigilo", "sigiloso", "ocultarse", "invisible", "invisibilidad",
    "teletransporte", "teletransportar", "portal", "portales",
    "invocacion", "invocar", "invocado", "invocador",
    "conjuro", "conjuros", "conjurar", "conjurador",
    "runa", "runas", "runico", "runica",
    "aura", "auras", "aurico",
    "totem", "totems", "totemica",
    "ritual", "rituales", "ritualista",
    "talismán", "amuleto", "amuletos",
    "pociones", "pocion", "pocionar", "alquimia",
    "alquimista", "alquimico",
    "flecha", "flechas", "flechar", "flecha de fuego",
    "espada", "espadas", "espadear",
    "hacha", "hachas", "lanza", "lanzar",
    "daga", "dagas", "dagear",
    "arco", "arcos", "arco largo",
    "baston", "bastones",
    "martillo", "martillos",
    "armadura", "armaduras",
    "casco", "cascos", "yelmo", "yelmos",
    "botas", "guantes", "capas", "capa",
    # ── Elementos ────────────────────────────────
    "fuego", "llamas", "llama", "incendio", "arder",
    "agua", "hielo", "glaciar", "congelar",
    "tierra", "terremoto", "piedra", "roca",
    "viento", "tornado", "tormenta", "rayo",
    "rayo", "rayos", "electrico", "trueno",
    "sombra", "sombras", "oscuridad", "tinieblas",
    "luz", "brillar", "brillo", "sagrado", "divino",
    "naturaleza", "planta", "veneno", "druid",
    "acido", "corrosion", "corroer",
    "psiquico", "mental", "telepatia",
    "fuerza bruta", "golpe", "impacto",
    # ── Misiones y mundo ────────────────────────
    "mision", "misiones", "quest", "aventura", "aventuras",
    "dungeon", "mazmorra", "mazmorras", "cueva", "cuevas",
    "aldea", "aldeas", "pueblo", "ciudad", "ciudades",
    "castillo", "castillos", "torre", "torres",
    "bosque", "bosques", "selva", "selvas",
    "montaña", "montañas", "volcan", "volcanes",
    "desierto", "desiertos", "llanura", "llanuras",
    "oceano", "mar", "rio", "lago",
    "isla", "islas", "archipelago",
    "guarida", "guaridas", "escondite",
    "templo", "templos", "santuario",
    "taberna", "posada", "mercado",
    "mapa", "mapas", "brujula", "tesoro",
    "cofre", "cofres", "llave", "llaves",
    "trampa", "trampas", "tramposo",
    "escalera", "puerta", "puertas",
    "pasadizo", "laberinto",
    "recompensa", "recompensas",
    "experiencia", "nivel", "niveles",
    "puntos", "punto", "puntaje",
    "dinero", "monedas", "moneda", "oro", "plata",
    "gemas", "gema", "diamante", "rubi",
    "comercio", "comerciar", "comprar", "vender",
    "tienda", "tiendas", "herrero",
    "alquiler", "alquilar",
    "contrato", "contratos",
    "traicion", "traicionar",
    "alianza", "alianzas", "aliado",
    "enemigo", "enemigos", "rival",
    "jefe", "jefes", "boss",
    "minijefe", "subje",
    "horda", "hordas", "ejercito",
    "gremio", "gremios", "clan", "clanes",
    "faccion", "facciones",
    "reputacion", "fama", "infamia",
    "titulo", "titulos", "rango",
    # ── Monstruos y criaturas ───────────────────
    "dragon", "dragones", "wyvern", "basilisco",
    "hidra", "quimera", "grifo", "grifos",
    "fenix", "unicornio", "pegaso",
    "golem", "golems", "automata",
    "esqueleto", "esqueletos", "zombie", "zombies",
    "fantasma", "fantasmas", "espectro",
    "demonio", "demonios", "diablo",
    "angel", "angeles", "serafin",
    "gigante", "gigantes", "ciclope",
    "sirena", "sirenas", "tritón",
    "kraken", "leviatan", "behemot",
    "goblin", "goblins", "trasgo",
    "kobold", "kobolds",
    "minotauro", "centauro", "satiro",
    "naga", "nagas", "serpiente",
    "araña", "aranas", "insecto",
    "lobo", "lobos", "oso", "bestia",
    "slime", "slimes", "gelatina",
    "elemental", "elementales",
    "demogorgon", "lich", "liches",
    "vampiro", "vampiros", "wight",
    "banshee", "wraith", "poltergeist",
    "aboleth", "beholder", "mindflayer",
    # ── Acciones de chat ────────────────────────
    "atacar", "defender", "huir", "escapar",
    "negociar", "comerciar", "hablar", "dialogar",
    "explorar", "investigar", "buscar", "encontrar",
    "abrir", "cerrar", "empujar", "jalar",
    "saltar", "correr", "caminar", "trepar",
    "nadar", "volar", "teletransportarse",
    "descansar", "dormir", "comer", "beber",
    "robar", "engañar", "mentir", "persuadir",
    "intimidar", "seducir", "convencer",
    "curar", "revivir", "resurreccionar",
    "invocar", "convocar", "desterrar",
    "crafetear", "fabricar", "crear", "destruir",
    "mejorar", "reparar", "identificar",
    "equipar", "desequipar", "usar",
    "lanzar", "disparar", "arrojar",
    "bloquear", "esquivar", "parar",
    "concentrarse", "meditar", "preparar",
    "acechar", "emboscar", "sorprender",
    "retirarse", "rendirse", "capturar",
    "rescatar", "liberar", "proteger",
    "iluminar", "oscurecer", "revelar",
    "rastrear", "seguir", "perseguir",
    "interrogar", "torturar", "liberar",
    "celebrar", "festejar", "desafiar",
    "duelo", "torneo", "competir",
    # ── Estadísticas ────────────────────────────
    "salud", "vida", "puntos de vida", "hp",
    "mana", "energia", "stamina", "resistencia",
    "armadura", "defensa", "evasion", "bloqueo",
    "daño", "critico", "golpe critico",
    "velocidad de ataque", "velocidad movimiento",
    "rango", "alcance",
    "durabilidad", "peso", "carga",
    "suerte", "fortuna", "bendicion",
    "veneno resistencia", "fuego resistencia",
    "hielo resistencia", "rayo resistencia",
    "oscuridad resistencia", "insanes"
    # ── Narrativa y rol ──────────────────────────
    "personaje", "personajes", "protagonista",
    "antagonista", "heroe", "heroina", "villano",
    "historia", "lore", "trasfondo",
    "reino", "reinos", "imperio",
    "rey", "reina", "principe", "princesa",
    "noble", "nobles", "nobleza",
    "campesino", "aldeano", "ciudadano",
    "soldado", "soldados", "guardia",
    "mercenario", "mercenarios",
    "asesino", "asesina", "espía",
    "buscador", "buscadora",
    "viajero", "viajera",
    "sabio", "oraculo", "profeta",
    "hechicero oscuro", "archimago",
    "señor oscuro", "diosa", "dios",
    "profecia", "leyenda", "mito",
    "epopeya", "saga", "cronica",
    "artefacto", "reliquia", "antiguedad",
    "maldicion antigua", "bendicion divina",
    "pacto", "juramento", "promesa",
    "sacrificio", "ofrenda", "ritual",
    "eleccion", "destino", "libre albedrio",
    # ── Objetos especiales ──────────────────────
    "espada legendaria", "espada del destino",
    "escudo sagrado", "armadura dragon",
    "baston del archimago", "libro de hechizos",
    "grimorio", "tomo", "pergamino",
    "cristal magico", "orbe", "varita",
    "pocion de fuerza", "pocion curacion",
    "pocion invisibilidad", "pocion veneno",
    "elixir", "antidoto", "contraveneno",
    "anillo magico", "collar encantado",
    "brazalete poder", "cinto fuerza",
    "capa invisibilidad", "botas velocidad",
    "guantes destreza", "yelmo sabiduria",
    "llave maestra", "mapa del tesoro",
    "brujula magica", "catalejo",
    "espejo verdad", "bola de cristal",
    # ── Emociones y roleplay ─────────────────────
    "valiente", "cobarde", "temerario",
    "sabio", "impulsivo", "calculador",
    "leal", "traicionero", "honesto",
    "cruel", "amable", "misericordioso",
    "curioso", "desconfiado", "esperanzador",
    "desesperado", "determinado", "resignado",
    "furioso", "calmado", "sereno",
    "alegre", "triste", "melancólico",
    "asombrado", "horrorizado", "indiferente", "insano"
    # ── Comandos de juego ───────────────────────
    "inventario", "equipo", "estadisticas",
    "habilidades", "talentos", "perks",
    "registro", "diario", "bitacora",
    "configuracion", "opciones", "pausa",
    "guardar", "cargar", "nuevo juego",
    "tutorial", "ayuda", "pistas",
    "logros", "medallas", "trofeos",
    "ranking", "tabla", "clasificacion",
    "multijugador", "cooperativo", "competitivo",
    "servidor", "sala", "lobby",
    "chat", "mensaje", "mensajes",
    "emote", "reaccion", "emoji",
    "susurro", "gritar", "hablar normal",
    "grupo", "partido", "equipo",
    "lider", "comandante", "capitan",
    "unirse", "salir", "expulsar",
    "invitar", "aceptar", "rechazar",
    "amigos", "lista de amigos", "bloquear",
    "ignorar", "reportar", "denunciar",
]

# Eliminar duplicados y ordenar
RPG_VOCABULARY = sorted(set(w.lower() for w in RPG_VOCABULARY))
