"""
lo saque de chatgpt la verda
Vocabulario RPG (~1200 palabras) para el sistema de autocompletado.
"""

BLACKLIST_WORDS = [
    "idiota", "estupido","estupida" , "maldita", "mierda", "basura",
    "imbecil", "pendejo","pendeja", "cabron","cabrona", "puta", "tetas",
    "inutil", "animal", "bestia", "hitler", "nigga", "prostituta",
    "prostituto", "vagina", "pussy", "pene", "dick", "rape", "bitch",
    "malparido", "malparida", "67", "six", "seven", "sixseven", "coito",
    "sex", "sexo", "sexo2", "Trabajo", "chamba", "job", "agarrar la pala", "culos", "culo",
    
]

RPG_VOCABULARY = [
    # ── Clases y razas ──────────────────────────
    "guerrero", "guerrera", "mago", "maga", "hechicero", "hechicera",
    "arquero", "arquera", "paladin", "paladina", "druida", "druida",
    "barbaro", "barbara", "bardo", "bardesa", "clerigo", "cleriga",
    "picaro", "picara", "monje", "monjesa", "nigromante", "nigromanta",
    "cazador", "cazadora", "explorador", "exploradora", "guardian",
    "guardiana", "titan", "titana", "caballero", "caballera",
    "lanzero", "lanzera", "espadachin", "hechizero", "berserker", 
    "criomante", "geomante", "aeromante", "cronomante", "taumaturgo",
    "duelista", "templario", "cruzado", "chamán", "ilusionista",
    "vidente", "runista", "centinela", "mercader",  "piromante",
    "corsario", "gladiador", "juglar", "trovador",
    "alquimero", "arcanista", "elementalista",
    "espiritista", "taumaturga", "encantador",
    # Razas
    "elfo", "elfa", "enano", "enana", "hobbit", "gnomo", "gnoma",
    "orco", "orca", "troll", "hada", "fairy", "dragones", "draconido",
    "licántropo", "vampiro", "vampira", "semielfo", "semiorco",
    "tiefling", "aarakocra", "genasi", "goliath", "triton",
    "dríada", "oni", "yokai", "djinn", "efrit", "wendigo", "leshen", "otaku",
    # ── Habilidades y magia ──────────────────────
    "ataque", "ataques", "atacar", "atacante", "atacantes",
    "defensa", "defender", "defensas", "defensivo", "defensiva",
    "hechizo", "hechizos", "lanzar", "lanzamiento", "lanzador",
    "magia", "magico", "magica", "magicer", "magister",
    "encantamiento", "encantado", "encantadora", "encantar",
    "maldicion", "maldecir", "maldito", "maldiciente",
    "bendicion", "bendecir", "bendito", "bendita",
    "curacion", "curar", "curado", "curada", "curandero",
    "veneno", "envenenar", "envenenado", "venenos",
    "escudo", "escudos", "escudar", "proteger", "proteccion",
    "fuerza", "fuerte", "poder", "poderes", "poderoso",
    "agilidad", "agil", "velocidad", "veloz", "rapido",
    "inteligencia", "inteligente", "sabiduria", "sabio",
    "carisma", "carismatico", "intimidar", "intimidacion",
    "sigilo", "sigiloso", "ocultarse", "invisible", "invisibilidad",
    "teletransporte", "teletransportar", "portal", "portales",
    "invocacion", "invocar", "invocado", "invocador",
    "conjuro", "conjuros", "conjurar", "conjurador",
    "runa", "runas", "runico", "runica",
    "aura", "auras", "aurico", "taumaturgia", "nigromancia", "hidromancia",
    "totem", "totems", "totemica", "electromancia", "biomancia", "transmutación",
    "ritual", "rituales", "ritualista", "levitación", "clarividencia", "metamorfosis",
    "talismán", "amuleto", "amuletos", "regeneración", "petrificación", "ralentización",
    "pociones", "pocion", "pocionar", "alquimia",
    "alquimista", "alquimico", "purificación", "absorción", "disipación",
    "flecha", "flechas", "flechar", "flecha de fuego",
    "espada", "espadas", "espadear", "inmunidad", "vulnerabilidad", "penetración",
    "hacha", "hachas", "lanza", "lanzar", "devastación", "aniquilación", "fulminar",
    "daga", "dagas", "dagear", "incineración", "congelación", "electrificación",
    "arco", "arcos", "arco largo", "combustión", "implosión", "distorsión",
    "baston", "bastones", "manipulación", "sincronización", "catalizador",
    "martillo", "martillos", "resonancia", "afinidad", "corrupción",
    "armadura", "armaduras", "canalización", "contrahechizo", "fortificar",
    "casco", "cascos", "yelmo", "yelmos", "maleficio", "exorcismo", "posesión",
    "botas", "guantes", "capas", "capa", "dominación", "evocación", "abjuración",
    "embrujo", "sortilegio", "hechicería", "misticismo",

    # ── Elementos ────────────────────────────────
    "fuego", "llamas", "llama", "incendio", "arder",
    "agua", "hielo", "glaciar", "congelar",
    "tierra", "terremoto", "piedra", "roca",
    "viento", "tornado", "tormenta", "rayo",
    "rayo", "rayos", "electrico", "trueno",
    "sombra", "sombras", "oscuridad", "tinieblas",
    "luz", "brillar", "brillo", "sagrado", "divino",
    "naturaleza", "planta", "veneno", "druid",
    "acido", "corrosion", "corroer",
    "psiquico", "mental", "telepatia",
    "fuerza bruta", "golpe", "impacto", "energía astral",
    "maná oscuro", "esencia vital",
    "esencia demoníaca", "esencia celestial",
    "afinidad oscura", "afinidad luminosa",
    "corrupción ancestral", "azar",
    # ── Misiones y mundo ────────────────────────
    "mision", "misiones", "quest", "aventura", "aventuras",
    "dungeon", "mazmorra", "mazmorras", "cueva", "cuevas",
    "aldea", "aldeas", "pueblo", "ciudad", "ciudades",
    "castillo", "castillos", "torre", "torres",
    "bosque", "bosques", "selva", "selvas",
    "montaña", "montañas", "volcan", "volcanes",
    "desierto", "desiertos", "llanura", "llanuras",
    "oceano", "mar", "rio", "lago", "charco", 
    "isla", "islas", "archipelago", "caño",
    "guarida", "guaridas", "escondite", 
    "templo", "templos", "santuario", "sinagoga"
    "taberna", "posada", "mercado", "ara", "olimplica"
    "mapa", "mapas", "brujula", "tesoro", "one piece",
    "cofre", "cofres", "llave", "llaves", 
    "trampa", "trampas", "tramposo", "exploración profunda",
    "escalera", "puerta", "puertas", "casino", "poker", "blackjack",
    "pasadizo", "laberinto", "travesía", "ruleta", 
    "recompensa", "recompensas", "incursión"
    "experiencia", "nivel", "niveles", "apuestas"
    "puntos", "punto", "puntaje", "expedición",
    "dinero", "monedas", "moneda", "oro", "plata",
    "gemas", "gema", "diamante", "rubi", "asedio",
    "comercio", "comerciar", "comprar", "vender",
    "tienda", "tiendas", "herrero", "academia", "monasterio", "fortificación",
    "alquiler", "alquilar", "purgatorio", "abismo", "averno",
    "contrato", "contratos", "inframundo", "necropolis", "ciudadela",
    "traicion", "traicionar", "fortaleza", "bastión", "muralla",
    "alianza", "alianzas", "aliado", "observatorio", "biblioteca arcana",
    "enemigo", "enemigos", "rival", "embarcadero", "puerto", "astillero",
    "jefe", "jefes", "boss", "fortín", "cripta", "catacumba",
    "minijefe", "subjefe", "necrópolis antigua", "acantilado",
    "horda", "hordas", "ejercito", "tundra", "pantano", "ciénaga",
    "gremio", "gremios", "clan", "clanes", "clancito", 
    "faccion", "facciones", "paramo", "oasis", "arrecife",
    "reputacion", "fama", "infamia", "fiordo", "península", "barranco",
    "titulo", "titulos", "rango", "riscos", "coliseo", "anfiteatro",
    # ── Monstruos y criaturas ───────────────────
    "dragon", "dragones", "wyvern", "basilisco",
    "hidra", "quimera", "grifo", "grifos",
    "fenix", "unicornio", "pegaso", "revenant", "aberración",
    "golem", "golems", "automata", "androide", "alien", 
    "esqueleto", "esqueletos", "zombie", "zombies",
    "fantasma", "fantasmas", "espectro",
    "demonio", "demonios", "diablo", "gólem ígneo", "gólem glacial",
    "angel", "angeles", "serafin", "ufo", 
    "gigante", "gigantes", "ciclope", 
    "sirena", "sirenas", "tritón",
    "kraken", "leviatan", "behemot",
    "goblin", "goblins", "trasgo", "acechador", "devorador",
    "kobold", "kobolds", "mantícora", "arpía", "kelpie",
    "minotauro", "centauro", "satiro",
    "naga", "nagas", "serpiente",
    "araña", "aranas", "insecto", "basilisco anciano", "wyrm",
    "lobo", "lobos", "oso", "bestia",
    "slime", "slimes", "gelatina", "dracoliche", "necrófago", "ghoul",
    "elemental", "elementales", "roc", "ent", "gólem pétreo",
    "demogorgon", "lich", "liches", "dealer", "malvado dealer", 
    "vampiro", "vampiros", "wight",
    "banshee", "wraith", "poltergeist",
    "aboleth", "beholder", "mindflayer",
    "incel", "papuloco","diler", "woman",
    "Meowscarada",
    # ── Acciones de chat ────────────────────────
    "atacar", "defender", "huir", "escapar",
    "negociar", "comerciar", "hablar", "dialogar",
    "explorar", "investigar", "buscar", "encontrar",
    "abrir", "cerrar", "empujar", "jalar",
    "saltar", "correr", "caminar", "trepar",
    "nadar", "volar", "teletransportarse",
    "descansar", "dormir", "comer", "beber",
    "robar", "engañar", "mentir", "persuadir",
    "intimidar", "seducir", "convencer",
    "curar", "revivir", "resurreccionar",
    "invocar", "convocar", "desterrar",
    "crafetear", "fabricar", "crear", "destruir",
    "mejorar", "reparar", "identificar",
    "equipar", "desequipar", "usar", "acometer", "contraatacar",
    "lanzar", "disparar", "arrojar", "vigorizar", "embestir",
    "bloquear", "esquivar", "parar", "exterminar", "debilitar",
    "concentrarse", "meditar", "preparar",
    "acechar", "emboscar", "sorprender",
    "retirarse", "rendirse", "capturar",
    "rescatar", "liberar", "proteger",
    "iluminar", "oscurecer", "revelar",
    "rastrear", "seguir", "perseguir",
    "interrogar", "torturar", "liberar",
    "celebrar", "festejar", "desafiar",
    "duelo", "torneo", "competir", "llorar", 
    "saquear", "devastar", "ejecutar", "no", "si",
    "negar", "confirmar", "deducir", "aplacar", "maquinar", 

    # ── Estadísticas ────────────────────────────
    "salud", "vida", "puntos de vida", "hp",
    "mana", "energia", "stamina", "resistencia",
    "armadura", "defensa", "evasion", "bloqueo",
    "daño", "critico", "golpe critico",
    "velocidad de ataque", "velocidad movimiento",
    "rango", "alcance", "vitalidad", "ferocidad", "precisión",
    "durabilidad", "peso", "carga", "percepción", "concentración",
    "suerte", "fortuna", "bendicion", "disciplina", "temple", "voluntad",
    "veneno resistencia", "fuego resistencia", "resistencia mágica", "daño verdadero",
    "hielo resistencia", "rayo resistencia", "resistencia elemental",
    "oscuridad resistencia", "insanes" "probabilidad crítica", "evasión mágica",
    "resistencia física", "regeneración pasiva",
    # ── Narrativa y rol ──────────────────────────
    "personaje", "personajes", "protagonista",
    "antagonista", "heroe", "heroina", "villano",
    "historia", "lore", "trasfondo",
    "reino", "reinos", "imperio",
    "rey", "reina", "principe", "princesa",
    "noble", "nobles", "nobleza",
    "campesino", "aldeano", "ciudadano",
    "soldado", "soldados", "guardia",
    "mercenario", "mercenarios",
    "asesino", "asesina", "espía",
    "buscador", "buscadora","dioskamigod",
    "viajero", "viajera", "emperador", "emperatriz", "soberano",
    "sabio", "oraculo", "profeta", "soberana", "heraldo", "inquisidor",
    "hechicero oscuro", "archimago", "inquisidora", "estratega",
    "señor oscuro", "diosa", "dios", "comandante supremo", "vigía",
    "profecia", "leyenda", "mito", "custodio", "carcelero",
    "epopeya", "saga", "cronica", "navegante", "pirata",
    "artefacto", "reliquia", "antiguedad", "divinidad", "deidad",
    "maldicion antigua", "bendicion divina",
    "pacto", "juramento", "promesa", "bandolero", "forajido",
    "sacrificio", "ofrenda", "ritual",
    "eleccion", "destino", "libre albedrio",
    # ── Objetos especiales ──────────────────────
    "espadón", "mandoble", "estoque","espada legendaria", "espada del destino",
    "escudo sagrado", "armadura dragon", "cimitarra", "alabarda", "mangual",
    "baston del archimago", "libro de hechizos", "ballesta", "virote", "carcaj",
    "katana", "nodachi", "wakizashi", "tridente", "guadaña", "cetro", "rifle spartan",
    "grimorio", "tomo", "pergamino", "reliquiario", "filacteria", "relicario",
    "cristal magico", "orbe", "varita", "grimorio ancestral", "tomo prohibido",
    "pocion de fuerza", "pocion curacion", "emblema", "estandarte", "blasón",
    "pocion invisibilidad", "pocion veneno", "báculo", "medallón", "brazales",
    "elixir", "antidoto", "contraveneno", "acero valyrio", "pergamino prohibido",
    "anillo magico", "collar encantado", "diario arcano", "runario", "Aguijoneador"
    "brazalete poder", "cinto fuerza", "adamantita", "hierro negro", "acero rúnico",
    "capa invisibilidad", "botas velocidad", "hombreras", "grebas", "pechera",
    "guantes destreza", "yelmo sabiduria", "insignia imperial", "dmr", "totem de la imortalidad",
    "llave maestra", "mapa del tesoro", "cristal etéreo", "obsidiana", "mithril",
    "brujula magica", "catalejo", "reliquia ancestral", "gema astral", "Manzana de Notch", 
    "espejo verdad", "bola de cristal", "códice", "bestiario", "manuscrito",
    "peto", "visor", "coraza", "gargantilla", "Jetpack", "moto", "carro", "submarino"
    # ── Emociones y roleplay ─────────────────────
    "valiente", "cobarde", "temerario",
    "sabio", "impulsivo", "calculador",
    "leal", "traicionero", "honesto", "resentido", 
    "cruel", "amable", "misericordioso", "ansioso", 
    "curioso", "desconfiado", "esperanzador",
    "desesperado", "determinado", "resignado", "audaz", "estoico", "errante",
    "furioso", "calmado", "sereno", "nómada", "taciturno",
    "alegre", "triste", "melancólico", "sombrío", "luminoso",
    "asombrado", "horrorizado", "indiferente", "insano",
    "agradecido" "despiadado", "honorable", "vengativo",
    # ── Rereza y atributos ───────────────────────
    "espectral", "etéreo", "infernal",
    "celestial", "ancestral",
    "maldito ancestral", "titánico",
    "colosal", "legendario",
    "mítico", "épico",
    "inmortal", "imperecedero",
    "omnisciente", "omnipotente",
    "incorruptible", "mamalon"
    # ── Comandos de juego ───────────────────────
    "inventario", "equipo", "estadisticas",
    "habilidades", "talentos", "perks",
    "registro", "diario", "bitacora",
    "configuracion", "opciones", "pausa",
    "guardar", "cargar", "nuevo juego",
    "tutorial", "ayuda", "pistas", "Battlepass",
    "logros", "medallas", "trofeos",
    "ranking", "tabla", "clasificacion",
    "multijugador", "cooperativo", "competitivo",
    "servidor", "sala", "lobby", "Microtransacción"
    "chat", "mensaje", "mensajes",
    "emote", "reaccion", "emoji", "loot boxes", 
    "susurro", "gritar", "hablar normal",
    "grupo", "partido", "equipo", "Bracket",
    "lider", "comandante", "capitan",
    "unirse", "salir", "expulsar", "bannear"
    "invitar", "aceptar", "rechazar",
    "amigos", "lista de amigos", "bloquear",
    "ignorar", "reportar", "denunciar", "volumen", "bloquear", 
]

# Eliminar duplicados y ordenar
RPG_VOCABULARY = sorted(set(w.lower() for w in RPG_VOCABULARY))
